# Generated by Django 2.1.5 on 2019-03-01 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='email',
            new_name='Contact',
        ),
    ]
