# Generated by Django 2.1.7 on 2019-03-01 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190228_1853'),
        ('website', '0002_whoweare'),
    ]

    operations = [
    ]
