# Generated by Django 2.1.5 on 2019-03-01 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_whoweare'),
        ('website', '0002_auto_20190228_1853'),
    ]

    operations = [
    ]
