# Generated by Django 2.1.5 on 2019-03-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_merge_20190301_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
