# Generated by Django 2.1.5 on 2019-03-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_merge_20190301_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comentario',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
