# Generated by Django 2.1.7 on 2019-03-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contact_comentario'),
        ('website', '0005_ourhistory'),
    ]

    operations = [
    ]
